### ISSUE TITLE
passwd: Authentication token manipulation error

### ISSUE THREAD

**Issue by PeterNerlich** [lutzthies/robolab-docs-issue-tracker#1]
On every brick the default user robot has the password maker. For obvious reasons, it is strongly advised to change the default password. However, the command passwd does not seem to work as expected.

```robot@ev3dev:~$ passwd
Changing password for robot.
(current) UNIX password: 
passwd: Authentication token manipulation error
passwd: password unchanged
robot@ev3dev:~$ 
```

Using sudo passwd seems to work at first, but you will still need to use the old password on the next login. What works is to type sudo passwd $USER, where $USER is just an environment variable that reflects the currently logged in user — in this case always robot.

**Comment by lutzthies** [comment]
Has this problem been solved after entering the old password correctly?

**Comment by PeterNerlich** [comment]
I did not try again after reading your reply, since I solved it as described, but I'm confident I made sure I entered the password correctly multiple times when I hit that problem. `maker` being the default password, I deem the odds of accidentally misspelling it every time very unlikely.

**Comment by lutzthies** [comment]
Okay. However, I cannot reproduce your problem. Since it is the only time in an estimated 50 cases of changing the default password in the current release of the OS, this issue will be closed for now. I moved your post from the Auditorium here for the sake of completeness and edited the description of this issue accordingly. Thanks for your contribution.
